/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "njpolxhuzeobxvuqwiic"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qcG9seGh1emVvYnh2dXF3aWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgxODkyOTgsImV4cCI6MjA4Mzc2NTI5OH0.UEp6dP2Hiowp9qTySqmEgVdZsNL-jR2E7eWRSyol-_k"